config/routes.rb
Rails.application.routes.draw do
 resources:articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :load_article, only: [:edit, :update, :destroy, :show]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
  end

  def edit
  end

  def create
    Article.create(article_params)
  end

  def update
    @article.update_attributes(article_params)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

private

  def load_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>All articles</h1>
  <ul>
    <% @articles.each do |article| %>
      <li>
        <%= link_to article.title, article_path(article) %>
        <%= article.content %>
        <%= link_to "Edit", edit_article_path(article) %>
        <%= link_to "Delete", article_path(article),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
          <% end %>
      </li>
  </ul>

app/views/articles/new.html.erb
<% render 'form' %>

app/views/articles/show.html.erb
<h1>Show article</h1>
  <%= @article.title %>
  <%= @article.content %>
  <%= link_to "Edit", edit_article_path(@article)%>
  <%= link_to "delete", article_path(@article),
        method: :delete,
        data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>